My Project: PipelineWorker Class Reference
PipelineWorker Class Reference
Public Member Functions
PipelineWorker (Napi::Function callback, PipelineBaton *baton, Napi::Function debuglog, Napi::Function queueListener)
~PipelineWorker ()
void Execute ()
void OnOK ()
Constructor & Destructor Documentation
PipelineWorker()
PipelineWorker::PipelineWorker (Napi::Function callback, PipelineBaton * baton, Napi::Function debuglog, Napi::Function queueListener) inline
~PipelineWorker()
PipelineWorker::~PipelineWorker () inline
Member Function Documentation
Execute()
void PipelineWorker::Execute () inline
References sharp::InputDescriptor::access, sharp::ApplyAlpha(), sharp::AssertImageTypeDimensions(), sharp::Bandbool(), sharp::Blur(), sharp::Boolean(), sharp::CalculateCrop(), sharp::CalculateEmbedPosition(), sharp::Clahe(), sharp::Convolve(), sharp::counterProcess, sharp::counterQueue, sharp::CROP, sharp::CropMultiPage(), sharp::EMBED, sharp::EmbedMultiPage(), sharp::EnsureAlpha(), sharp::EnsureColourspace(), sharp::ExifOrientation(), sharp::Flatten(), sharp::Gamma(), sharp::GetPageHeight(), sharp::GetProfile(), sharp::GIF, Composite::gravity, sharp::HasAlpha(), Composite::hasOffset, sharp::HasProfile(), sharp::HEIF, Composite::input, sharp::Is16Bit(), sharp::IsDz(), sharp::IsDzZip(), sharp::IsGif(), sharp::IsHeif(), sharp::IsJp2(), sharp::IsJpeg(), sharp::IsJxl(), sharp::IsPng(), sharp::IsTiff(), sharp::IsV(), sharp::IsWebp(), sharp::JP2, sharp::JPEG, sharp::JXL, Composite::left, sharp::Linear(), Composite::mode, sharp::Modulate(), sharp::Negate(), sharp::Normalise(), sharp::OpenInput(), sharp::PDF, sharp::PNG, Composite::premultiplied, sharp::RAW, sharp::Recomb(), sharp::RemoveAlpha(), sharp::RemoveAnimationProperties(), sharp::RemoveExif(), sharp::RemoveExifOrientation(), sharp::RemoveGifPalette(), sharp::ResolveShrink(), sharp::SetAnimationProperties(), sharp::SetDensity(), sharp::SetExifOrientation(), sharp::SetProfile(), sharp::SetTimeout(), sharp::Sharpen(), sharp::StaySequential(), sharp::SVG, sharp::Threshold(), sharp::TIFF, Composite::tile, sharp::Tint(), Composite::top, sharp::Trim(), sharp::Unflatten(), sharp::UNKNOWN, sharp::VIPS, sharp::VipsWarningCallback(), and sharp::WEBP.
OnOK()
void PipelineWorker::OnOK () inline
References sharp::counterProcess, sharp::counterQueue, sharp::FreeCallback, Composite::input, STAT64_FUNCTION, STAT64_STRUCT, sharp::TrimEnd(), and sharp::VipsWarningPop().
The documentation for this class was generated from the following file:
C:/Users/arisc/OneDrive/Documents/GitHub/FINAL/EcoEats-Project/node_modules/sharp/src/pipeline.cc