My Project: MetadataWorker Class Reference
MetadataWorker Class Reference
Public Member Functions
MetadataWorker (Napi::Function callback, MetadataBaton *baton, Napi::Function debuglog)
~MetadataWorker ()
void Execute ()
void OnOK ()
Constructor & Destructor Documentation
MetadataWorker()
MetadataWorker::MetadataWorker (Napi::Function callback, MetadataBaton * baton, Napi::Function debuglog) inline
~MetadataWorker()
MetadataWorker::~MetadataWorker () inline
Member Function Documentation
Execute()
void MetadataWorker::Execute () inline
References sharp::counterQueue, sharp::ExifOrientation(), sharp::GetDensity(), sharp::HasAlpha(), sharp::HasDensity(), sharp::HasProfile(), sharp::ImageTypeId(), and sharp::UNKNOWN.
OnOK()
void MetadataWorker::OnOK () inline
References sharp::FreeCallback, sharp::TrimEnd(), and sharp::VipsWarningPop().
The documentation for this class was generated from the following file:
C:/Users/arisc/OneDrive/Documents/GitHub/FINAL/EcoEats-Project/node_modules/sharp/src/metadata.cc