My Project: StatsWorker Class Reference
StatsWorker Class Reference
Public Member Functions
StatsWorker (Napi::Function callback, StatsBaton *baton, Napi::Function debuglog)
~StatsWorker ()
void Execute ()
void OnOK ()
Public Attributes
const int STAT_MIN_INDEX = 0
const int STAT_MAX_INDEX = 1
const int STAT_SUM_INDEX = 2
const int STAT_SQ_SUM_INDEX = 3
const int STAT_MEAN_INDEX = 4
const int STAT_STDEV_INDEX = 5
const int STAT_MINX_INDEX = 6
const int STAT_MINY_INDEX = 7
const int STAT_MAXX_INDEX = 8
const int STAT_MAXY_INDEX = 9
Constructor & Destructor Documentation
StatsWorker()
StatsWorker::StatsWorker (Napi::Function callback, StatsBaton * baton, Napi::Function debuglog) inline
~StatsWorker()
StatsWorker::~StatsWorker () inline
Member Function Documentation
Execute()
void StatsWorker::Execute () inline
References sharp::counterQueue, sharp::HasAlpha(), sharp::MaximumImageAlpha(), sharp::RemoveAlpha(), STAT_MAX_INDEX, STAT_MAXX_INDEX, STAT_MAXY_INDEX, STAT_MEAN_INDEX, STAT_MIN_INDEX, STAT_MINX_INDEX, STAT_MINY_INDEX, STAT_SQ_SUM_INDEX, STAT_STDEV_INDEX, STAT_SUM_INDEX, stats(), and sharp::UNKNOWN.
OnOK()
void StatsWorker::OnOK () inline
References sharp::TrimEnd(), and sharp::VipsWarningPop().
Member Data Documentation
STAT_MAX_INDEX
const int StatsWorker::STAT_MAX_INDEX = 1
Referenced by Execute().
STAT_MAXX_INDEX
const int StatsWorker::STAT_MAXX_INDEX = 8
Referenced by Execute().
STAT_MAXY_INDEX
const int StatsWorker::STAT_MAXY_INDEX = 9
Referenced by Execute().
STAT_MEAN_INDEX
const int StatsWorker::STAT_MEAN_INDEX = 4
Referenced by Execute().
STAT_MIN_INDEX
const int StatsWorker::STAT_MIN_INDEX = 0
Referenced by Execute().
STAT_MINX_INDEX
const int StatsWorker::STAT_MINX_INDEX = 6
Referenced by Execute().
STAT_MINY_INDEX
const int StatsWorker::STAT_MINY_INDEX = 7
Referenced by Execute().
STAT_SQ_SUM_INDEX
const int StatsWorker::STAT_SQ_SUM_INDEX = 3
Referenced by Execute().
STAT_STDEV_INDEX
const int StatsWorker::STAT_STDEV_INDEX = 5
Referenced by Execute().
STAT_SUM_INDEX
const int StatsWorker::STAT_SUM_INDEX = 2
Referenced by Execute().
The documentation for this class was generated from the following file:
C:/Users/arisc/OneDrive/Documents/GitHub/FINAL/EcoEats-Project/node_modules/sharp/src/stats.cc