My Project: backend.recommendation_engine Namespace Reference
backend.recommendation_engine Namespace Reference
Functions
str normalize_ingredient_name (str ingredient)
float calculate_ingredient_match_score (List[str] recipe_ingredients, List[str] available_ingredients)
float calculate_expiration_urgency_score (List[InventoryItemModel] inventory_items, List[str] recipe_ingredients)
float calculate_recipe_complexity_score (RecipeModel recipe)
List[RecipeModel] get_recipe_recommendations (Session db, List[InventoryItemModel] inventory_items, int limit=10)
Function Documentation
calculate_expiration_urgency_score()
float backend.recommendation_engine.calculate_expiration_urgency_score (List[InventoryItemModel] inventory_items, List[str] recipe_ingredients)
Calculate urgency score based on expiring ingredients used in recipe
References normalize_ingredient_name().
Referenced by get_recipe_recommendations().
calculate_ingredient_match_score()
float backend.recommendation_engine.calculate_ingredient_match_score (List[str] recipe_ingredients, List[str] available_ingredients)
Calculate exact ingredient match score - only return 1.0 if ALL ingredients are available
References normalize_ingredient_name().
Referenced by get_recipe_recommendations().
calculate_recipe_complexity_score()
float backend.recommendation_engine.calculate_recipe_complexity_score (RecipeModel recipe)
Calculate complexity score - simpler recipes get higher scores
Referenced by get_recipe_recommendations().
get_recipe_recommendations()
List[RecipeModel] backend.recommendation_engine.get_recipe_recommendations (Session db, List[InventoryItemModel] inventory_items, int limit = 10)
Get recipe recommendations based on available inventory - only exact matches
References calculate_expiration_urgency_score(), calculate_ingredient_match_score(), and calculate_recipe_complexity_score().
normalize_ingredient_name()
str backend.recommendation_engine.normalize_ingredient_name (str ingredient)
Normalize ingredient names for better matching
Referenced by calculate_expiration_urgency_score(), and calculate_ingredient_match_score().