My Project: backend.populate_inventory Namespace Reference
backend.populate_inventory Namespace Reference
Functions
add_inventory_items ()
Variables
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://ecoeats_user:secure_password_123@ecoeats-db.c123456789.us-east-2.rds.amazonaws.com:5432/ecoeats_db")
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Function Documentation
add_inventory_items()
backend.populate_inventory.add_inventory_items ()
References add_inventory_items(), and SessionLocal.
Referenced by add_inventory_items().
Variable Documentation
DATABASE_URL
backend.populate_inventory.DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://ecoeats_user:secure_password_123@ecoeats-db.c123456789.us-east-2.rds.amazonaws.com:5432/ecoeats_db")
engine
backend.populate_inventory.engine = create_engine(DATABASE_URL)
SessionLocal
backend.populate_inventory.SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Referenced by add_inventory_items().