My Project: simple_debug Namespace Reference
simple_debug Namespace Reference
Functions
str normalize_ingredient_name (str ingredient)
test_matching ()
Function Documentation
normalize_ingredient_name()
str simple_debug.normalize_ingredient_name (str ingredient)
Normalize ingredient names for better matching - copied from backend
Referenced by test_matching().
test_matching()
simple_debug.test_matching ()
References normalize_ingredient_name(), and test_matching().
Referenced by test_matching().