My Project: C:/Users/arisc/OneDrive/Documents/GitHub/FINAL/EcoEats-Project/node_modules/sharp/src/pipeline.h File Reference
pipeline.h File Reference
#include <memory>
#include <string>
#include <vector>
#include <unordered_map>
#include <napi.h>
#include <vips/vips8>
#include "./common.h"
Classes
struct Composite
struct PipelineBaton
Functions
Napi::Value pipeline (const Napi::CallbackInfo &info)
Function Documentation
pipeline()
Napi::Value pipeline (const Napi::CallbackInfo & info)
References PipelineBaton::affineBackground, PipelineBaton::affineIdx, PipelineBaton::affineIdy, PipelineBaton::affineInterpolator, PipelineBaton::affineMatrix, PipelineBaton::affineOdx, PipelineBaton::affineOdy, PipelineBaton::angle, sharp::AttrAsBool(), sharp::AttrAsDouble(), sharp::AttrAsEnum(), sharp::AttrAsInt32(), sharp::AttrAsInt32Vector(), sharp::AttrAsStr(), sharp::AttrAsUint32(), sharp::AttrAsVectorOfDouble(), PipelineBaton::bandBoolOp, PipelineBaton::blurSigma, PipelineBaton::boolean, PipelineBaton::booleanOp, PipelineBaton::brightness, PipelineBaton::canvas, PipelineBaton::claheHeight, PipelineBaton::claheMaxSlope, PipelineBaton::claheWidth, PipelineBaton::colourspace, PipelineBaton::colourspacePipeline, PipelineBaton::composite, PipelineBaton::convKernel, PipelineBaton::convKernelHeight, PipelineBaton::convKernelOffset, PipelineBaton::convKernelScale, PipelineBaton::convKernelWidth, sharp::counterQueue, sharp::CreateInputDescriptor(), sharp::CROP, PipelineBaton::delay, sharp::EMBED, PipelineBaton::ensureAlpha, PipelineBaton::extendBackground, PipelineBaton::extendBottom, PipelineBaton::extendLeft, PipelineBaton::extendRight, PipelineBaton::extendTop, PipelineBaton::extendWith, PipelineBaton::extractChannel, PipelineBaton::fastShrinkOnLoad, PipelineBaton::fileOut, PipelineBaton::flatten, PipelineBaton::flattenBackground, PipelineBaton::flip, PipelineBaton::flop, PipelineBaton::formatOut, PipelineBaton::gamma, PipelineBaton::gammaOut, PipelineBaton::gifBitdepth, PipelineBaton::gifDither, PipelineBaton::gifEffort, PipelineBaton::gifInterFrameMaxError, PipelineBaton::gifInterPaletteMaxError, PipelineBaton::gifProgressive, PipelineBaton::gifReuse, PipelineBaton::greyscale, sharp::HasAttr(), PipelineBaton::heifBitdepth, PipelineBaton::heifChromaSubsampling, PipelineBaton::heifCompression, PipelineBaton::heifEffort, PipelineBaton::heifLossless, PipelineBaton::heifQuality, PipelineBaton::height, PipelineBaton::heightPost, PipelineBaton::heightPre, PipelineBaton::hue, sharp::IGNORE_ASPECT, Composite::input, PipelineBaton::input, PipelineBaton::joinChannelIn, PipelineBaton::jp2ChromaSubsampling, PipelineBaton::jp2Lossless, PipelineBaton::jp2Quality, PipelineBaton::jp2TileHeight, PipelineBaton::jp2TileWidth, PipelineBaton::jpegChromaSubsampling, PipelineBaton::jpegOptimiseCoding, PipelineBaton::jpegOptimiseScans, PipelineBaton::jpegOvershootDeringing, PipelineBaton::jpegProgressive, PipelineBaton::jpegQuality, PipelineBaton::jpegQuantisationTable, PipelineBaton::jpegTrellisQuantisation, PipelineBaton::jxlDecodingTier, PipelineBaton::jxlDistance, PipelineBaton::jxlEffort, PipelineBaton::jxlLossless, PipelineBaton::keepMetadata, PipelineBaton::kernel, PipelineBaton::leftOffsetPost, PipelineBaton::leftOffsetPre, PipelineBaton::lightness, PipelineBaton::linearA, PipelineBaton::linearB, PipelineBaton::loop, sharp::MAX, PipelineBaton::medianSize, sharp::MIN, PipelineBaton::minAmpl, PipelineBaton::negate, PipelineBaton::negateAlpha, PipelineBaton::normalise, PipelineBaton::normaliseLower, PipelineBaton::normaliseUpper, PipelineBaton::pngAdaptiveFiltering, PipelineBaton::pngBitdepth, PipelineBaton::pngCompressionLevel, PipelineBaton::pngDither, PipelineBaton::pngEffort, PipelineBaton::pngPalette, PipelineBaton::pngProgressive, PipelineBaton::pngQuality, PipelineBaton::position, PipelineBaton::precision, PipelineBaton::rawDepth, PipelineBaton::recombMatrix, PipelineBaton::removeAlpha, PipelineBaton::resizeBackground, PipelineBaton::rotateBeforePreExtract, PipelineBaton::rotationAngle, PipelineBaton::rotationBackground, PipelineBaton::saturation, PipelineBaton::sharpenM1, PipelineBaton::sharpenM2, PipelineBaton::sharpenSigma, PipelineBaton::sharpenX1, PipelineBaton::sharpenY2, PipelineBaton::sharpenY3, PipelineBaton::threshold, PipelineBaton::thresholdGrayscale, PipelineBaton::tiffBitdepth, PipelineBaton::tiffCompression, PipelineBaton::tiffMiniswhite, PipelineBaton::tiffPredictor, PipelineBaton::tiffPyramid, PipelineBaton::tiffQuality, PipelineBaton::tiffResolutionUnit, PipelineBaton::tiffTile, PipelineBaton::tiffTileHeight, PipelineBaton::tiffTileWidth, PipelineBaton::tiffXres, PipelineBaton::tiffYres, PipelineBaton::tileAngle, PipelineBaton::tileBackground, PipelineBaton::tileBasename, PipelineBaton::tileCentre, PipelineBaton::tileContainer, PipelineBaton::tileDepth, PipelineBaton::tileFormat, PipelineBaton::tileId, PipelineBaton::tileLayout, PipelineBaton::tileOverlap, PipelineBaton::tileSize, PipelineBaton::tileSkipBlanks, PipelineBaton::timeoutSeconds, PipelineBaton::tint, PipelineBaton::topOffsetPost, PipelineBaton::topOffsetPre, PipelineBaton::trimBackground, PipelineBaton::trimLineArt, PipelineBaton::trimThreshold, PipelineBaton::unflatten, PipelineBaton::useExifOrientation, PipelineBaton::webpAlphaQuality, PipelineBaton::webpEffort, PipelineBaton::webpLossless, PipelineBaton::webpMinSize, PipelineBaton::webpMixed, PipelineBaton::webpNearLossless, PipelineBaton::webpPreset, PipelineBaton::webpQuality, PipelineBaton::webpSmartSubsample, PipelineBaton::width, PipelineBaton::widthPost, PipelineBaton::widthPre, PipelineBaton::withExif, PipelineBaton::withExifMerge, PipelineBaton::withIccProfile, PipelineBaton::withMetadataDensity, PipelineBaton::withMetadataOrientation, PipelineBaton::withoutEnlargement, and PipelineBaton::withoutReduction.
Referenced by init().