My Project: C:/Users/arisc/OneDrive/Documents/GitHub/FINAL/EcoEats-Project/node_modules/sharp/src/sharp.cc File Reference
sharp.cc File Reference
#include <mutex>
#include <napi.h>
#include <vips/vips8>
#include "common.h"
#include "metadata.h"
#include "pipeline.h"
#include "utilities.h"
#include "stats.h"
Functions
Napi::Object init (Napi::Env env, Napi::Object exports)
Function Documentation
init()
Napi::Object init (Napi::Env env, Napi::Object exports)
References _isUsingJemalloc(), _maxColourDistance(), block(), cache(), concurrency(), counters(), format(), libvipsVersion(), metadata(), pipeline(), simd(), stats(), and sharp::VipsWarningCallback().