My Project: C:/Users/arisc/OneDrive/Documents/GitHub/FINAL/EcoEats-Project/node_modules/sharp/src/stats.cc File Reference
stats.cc File Reference
#include <numeric>
#include <vector>
#include <iostream>
#include <napi.h>
#include <vips/vips8>
#include "common.h"
#include "stats.h"
Classes
class StatsWorker
Functions
Napi::Value stats (const Napi::CallbackInfo &info)
Function Documentation
stats()
Napi::Value stats (const Napi::CallbackInfo & info)
References sharp::InputDescriptor::access, sharp::counterQueue, sharp::CreateInputDescriptor(), and StatsBaton::input.
Referenced by StatsWorker::Execute(), and init().