My Project: C:/Users/arisc/OneDrive/Documents/GitHub/FINAL/EcoEats-Project/node_modules/sharp/src/utilities.h File Reference
utilities.h File Reference
#include <napi.h>
Functions
Napi::Value cache (const Napi::CallbackInfo &info)
Napi::Value concurrency (const Napi::CallbackInfo &info)
Napi::Value counters (const Napi::CallbackInfo &info)
Napi::Value simd (const Napi::CallbackInfo &info)
Napi::Value libvipsVersion (const Napi::CallbackInfo &info)
Napi::Value format (const Napi::CallbackInfo &info)
void block (const Napi::CallbackInfo &info)
Napi::Value _maxColourDistance (const Napi::CallbackInfo &info)
Napi::Value _isUsingJemalloc (const Napi::CallbackInfo &info)
Function Documentation
_isUsingJemalloc()
Napi::Value _isUsingJemalloc (const Napi::CallbackInfo & info)
Referenced by init().
_maxColourDistance()
Napi::Value _maxColourDistance (const Napi::CallbackInfo & info)
References sharp::DetermineImageType(), sharp::HasAlpha(), and sharp::UNKNOWN.
Referenced by init().
block()
void block (const Napi::CallbackInfo & info)
Referenced by init().
cache()
Napi::Value cache (const Napi::CallbackInfo & info)
References cache().
Referenced by cache(), and init().
concurrency()
Napi::Value concurrency (const Napi::CallbackInfo & info)
Referenced by init().
counters()
Napi::Value counters (const Napi::CallbackInfo & info)
References sharp::counterProcess, sharp::counterQueue, and counters().
Referenced by counters(), and init().
format()
Napi::Value format (const Napi::CallbackInfo & info)
References format().
Referenced by format(), and init().
libvipsVersion()
Napi::Value libvipsVersion (const Napi::CallbackInfo & info)
Referenced by init().
simd()
Napi::Value simd (const Napi::CallbackInfo & info)
Referenced by init().